version: "3.7"

services:
  db:
    image: "${SQL_IMAGE_NAME}:${SQL_IMAGE_VERSION}"
    volumes:
      - ${SQL_VOLUME}
    restart: always
    env_file:
      - .envdb

  nginx:
    depends_on:
      - db
    image: "${NGINX_IMAGE_NAME}:${NGINX_IMAGE_VERSION}"
    volumes:
      - ${NGINX_VOLUME}
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    env_file:
      - .envnginx

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - .envphpadmin

volumes:
  db_data: {}
  nginx_data: {}