version: "3.7"
    
services:
  db:
    image: "${SQL_IMAGE_NAME}:${SQL_IMAGE_VERSION}"
    volumes:
      - ${SQL_VOLUME}
    restart: always
    env_file:
      - .envdb
    
  wordpress:
    depends_on:
      - db
    image: "${WORDPRESS_IMAGE_NAME}:${WORDPRESS_IMAGE_VERSION}"
    volumes:
      - ${WORDPRESS_VOLUME}
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    env_file:
      - .envwordpress

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - .envphpadmin

volumes:
  db_data: {}
  wordpress_data: {}